inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  NewCops: enable

require:
  - rubocop-rails-omakase
  - rubocop-performance

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
